config/routes.rb
UncollegeDatabase::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :activities
  match 'popular', to: 'activities#popular'

  resources :interests

  resources :user_sessions

  resources :users

  match '/users/sign_in', to: 'authentications#new'
  match '/auth/:provider/callback' => 'authentications#create'

  root to: 'users#splash'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
         can :splash, User
         can :manage, User do |this_user|
           this_user.id == user.id
         end
         can :create, UserSession
         can :destroy, UserSession do |this_session|
           this_session == current_user_session
         end
         can :create, Interest
         can :manage, Interest do |this_interest|
           this_interest.user_id == user.id
         end
         can [:create, :index, :show, :popular], Activity

       end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_searchable :name

  has_many :interests, dependent: :destroy
  accepts_nested_attributes_for :interests, allow_destroy: true
  has_many :users, through: :interests
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

  def provider_name
    if provider == 'open_id'
      "OpenID"
    else
      provider.titleize
    end
  end
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :activity, counter_cache: true
  belongs_to :user, counter_cache: true

  delegate :name, to: :activity

  def activity_name
    activity.try(:name)
  end

  def activity_name=(name)
    self.activity = Activity.find_or_create_by_name(name) if name.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :city,
                  :job, :college

  #acts_as_authentic do |config|
  #  config.crypto_provider = Authlogic::CryptoProviders::MD5
  #  #Add more options here if needed
  #end

  has_many :interests
  accepts_nested_attributes_for :interests, allow_destroy: true
  has_many :activities, through: :interests

  has_many :authentications

  def apply_omniauth(omniauth)
    self.email = omniauth['info']['email'] unless email
    self.name = omniauth['info']['name'] unless name
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
end

app/models/user_session.rb
class UserSession < ActiveRecord::Base
end

app/controllers/activities_controller.rb
class ActivitiesController < AuthorizedController
  load_and_authorize_resource

  make_resourceful do
    actions :new, :create, :update, :edit, :destroy, :show
  end

  def index
    @search = Activity.search(params[:search])
    @activities = @search.all
  end

  def popular
    @search = Activity.search(params[:search])
    @activities = @search.all(order: 'interests_count DESC')
    render 'activities/index'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #helper_method :current_user

  private

  #def current_user_session
  #  return @current_user_session if defined?(@current_user_session)
  #  @current_user_session = UserSession.find
  #end
  #
  #def current_user
  #  return @current_user if defined?(@current_user)
  #  @current_user = current_user_session && current_user_session.record
  #end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def handle_unverified_request
    true
  end

  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/authorized_controller.rb
class AuthorizedController < ApplicationController
  before_filter :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url , :alert => exception.message
  end
end

app/controllers/interests_controller.rb
class InterestsController < AuthorizedController
  load_and_authorize_resource
  make_resourceful do
    actions :new, :show, :edit, :create, :index, :update
  end

  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy

    redirect_to activities_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end

  private

  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/controllers/user_sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  load_and_authorize_resource

  make_resourceful do
    actions :new, :create
  end

  #this isn't called!
  def destroy
    user_session.destroy
    redirect_to registrations_path
  end

end

app/controllers/users_controller.rb
class UsersController < AuthorizedController
  load_and_authorize_resource

  make_resourceful do
    actions :index, :show, :new, :edit, :create, :destroy
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:city] == ENV['admin_password']
      @user.update_attribute(:admin, true)
      redirect_to "/users/#{params[:id]}"
    else
      @user.update_attributes(params[:user])
      redirect_to "/users/#{params[:id]}"
    end
  end


  def splash
    render 'user_sessions/splash'
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.haml
= form_for @activity do |f|
  -if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

= simple_form_for @search do |f|
  .field
    =f.label :name_contains
    =f.text_field :name_contains
  .clear
  =f.submit "Search"

Sort by
= sort_link @search, :name
\|
= link_to "Popularity", '/popular'

%table
  %tr
    %th Name
    %th Interested                
    %th Mentors
    %th Mentees
    %th

  - @activities.each do |activity|
    -if activity.interests.count > 0
      %tr
        %td= link_to activity.name, activity
        %td= activity.interests.count
        %td= activity.interests.where(wants_to_mentor: true).count
        %td= activity.interests.where(wants_to_be_mentored: true).count

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b= @activity.name

%p
  Mentors:
  - @activity.interests.where(wants_to_mentor: true).each do |interest, user = interest.user|
    %br
    = link_to user.name, interest_path(interest.id)
    = user.email

%p
  Mentees:
  - @activity.interests.where(wants_to_be_mentored: true).each do |interest, user = interest.user|
    %br
    = link_to user.name, interest_path(interest.id)
    = user.email

%p
  All interested:
  - @activity.interests.each do |interest, user = interest.user|
    %br
    = link_to user.name, interest_path(interest.id)
    = user.email

app/views/authentications/_authentications.html.haml
-if authentications
  -unless authentications.empty?
    %p
      %strong You can sign in to this account using:
    .authentications
      -for authentication in authentications
        .authentication
          = image_tag "#{authentication.provider}_32.png", :size => "32x32"
          .provider= authentication.provider.titleize
          .uid= authentication.uid
          = link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove"
          .clear

  %p
    %strong Add another service to sign in with:
- else
  %p
    %strong Sign in through facebook
    -#one of these services:

-#%a(href="/auth/twitter" class="auth_provider")
  = image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter"
  Twitter
%a(href="/auth/facebook" class="auth_provider")
  = image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook"
  Facebook
-#%a(href="/auth/google_apps" class="auth_provider")
  = image_tag "google_64.png", :size => "64x64", :alt => "Google"
  Google
-#%a(href="/auth/open_id" class="auth_provider")
  = image_tag "openid_64.png", :size => "64x64", :alt => "OpenID"
  OpenID
.clear

app/views/authentications/index.html.haml
%title Sign In

= render 'authentications/authentications', authentications: @authentications

app/views/interests/_form.html.haml
= simple_form_for @interest do |f|
  -if @interest.errors.any?
    #error_explanation
      %h2= "#{pluralize(@interest.errors.count, "error")} prohibited this interest from being saved:"
      %ul
        - @interest.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :user_id, value: current_user.id
  .field
    = f.label :activity_name
    = f.text_field :activity_name, data: {autocomplete_source: Activity.order(:name).map(&:name)}
  .field= f.input :notes, :input_html => { :cols => 50, :rows => 10 }
  .field= f.input :wants_to_mentor
  .field= f.input :wants_to_be_mentored
  .actions= f.submit 'Save'

app/views/interests/edit.html.haml
%h1 Editing interest

= render 'form'

= link_to 'Show', @interest
\|
= link_to 'Back', interests_path

app/views/interests/index.html.haml
%h1 Listing interests

%table
  %tr
    %th User
    %th Activity
    %th Notes
    %th Mentor?
    %th Mentee?
    %th
    %th
    %th

  - @interests.each do |interest|
    %tr
      %td= link_to interest.user.name, user_path(interest.user_id)
      %td= link_to interest.activity.name, activity_path(interest.activity_id)
      %td= interest.notes
      %td= interest.wants_to_mentor
      %td= interest.wants_to_be_mentored
      %td= link_to 'Show', interest
      %td= link_to 'Edit', edit_interest_path(interest)
      %td= link_to 'Destroy', interest, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Interest', new_interest_path

app/views/interests/new.html.haml
%h1 New interest

= render 'form'

= link_to 'Back', interests_path

app/views/interests/show.html.haml
%p#notice= notice

%p
  %b User:
  = link_to @interest.user.name, user_path(@interest.user_id)

%p
  %b Activity:
  = link_to @interest.activity.name, activity_path(@interest.activity_id)
%p
  -if @interest.notes.length > 1
    %b Notes:
    = @interest.notes
  -else
    There are no notes on this user's interest.
-if @interest.wants_to_mentor
  %p
    %b Wants to mentor
-if @interest.wants_to_be_mentored
  %p
    %b Wants to be mentored

= link_to 'Edit', edit_interest_path(@interest) if can? :update, @interest

= link_to 'Destroy', @interest, confirm: 'Are you sure?', method: :delete if can? :delete, @interest

app/views/layouts/_header.html.haml
-if user_signed_in?
  .big= link_to "users", users_path
  .big= link_to "interests", activities_path
  .big= link_to "Add your interest!", new_interest_path
  .signin_text
    Signed in as
    = link_to current_user.name, current_user
    %br
    Not you?
    = link_to "Sign out", destroy_user_session_path, :method => :delete
-else

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title UncollegeDatabase
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield

app/views/user_sessions/new.html.haml
= simple_form_for @user_session do |f|
  .field= f.input :email
  .field= f.input :password
  .actions= f.submit

app/views/user_sessions/splash.html.haml
%h2 Welcome to the UnCollege Interests Database!
Add your interests, find like-minded people,
then get out of here and live.
%br

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field= f.input :name
  .field= f.input :email
  .field= f.input :password
  .field= f.input :password_confirmation
  .field= f.input :city
  .field= f.input :college
  .field= f.input :job
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th City
    %th College
    %th Job

  - @users.each do |user|
    %tr
      %td= link_to user.name, user
      %td= user.email
      %td= user.city
      %td= user.college
      %td= user.job
      %td= link_to 'Edit', edit_user_path(user) if can? :update, user
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete if can? :delete, user

%br

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b City:
  = @user.city
%p
  %b College:
  = @user.college
%p
  %b Job:
  = @user.job

%p
  Activities:
  -@user.interests.each do |interest, activity = interest.activity|
    %br
    = link_to activity.name, interest_path(interest.id)
    = "Mentor!" if interest.wants_to_mentor
    = "Mentee" if interest.wants_to_be_mentored

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path